apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: silver
type: Opaque
stringData:
  POSTGRES_USER: your_pg_user
  POSTGRES_PASSWORD: your_pg_password
  POSTGRES_DB: silver_map
